version: "3.7"

services:
  db:
    image: postgres:9.6
    restart: always
    env_file:
      - ../database/pg_hba.conf
      - ../database/postgresql.conf
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_DB: ddev
    volumes:
      - "../database:/docker-entrypoint-initdb.d/"
    container_name: postgres_cliff
  api:
    build: .
    ports:
      - 8080:8080
    volumes:
      - "/tmp:/tmp"
    container_name: ddev
    depends_on:
      - db
